repository: operator
upstream: tektoncd/operator
components:
- operator
- webhook
- proxy
# - bundle
# - index
github:
  update-sources: |
    # Update operator's payload and stuff
    make sources/operator/fetch-payload
branches:
- version: 1.17
  # upstream: …
  upstream: main
