repository: operator
upstream: tektoncd/operator
components:
- operator
- webhook
- proxy
# - bundle
# - index
github:
  update-sources: |
    - name: fetch-payload
      run: |
        # Operator SDK
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.37.0
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${RUNNER_OS}_${RUNNER_ARCH}
        chmod +x operator-sdk_${RUNNER_OS}_${RUNNER_ARCH} && sudo mv operator-sdk_${RUNNER_OS}_${RUNNER_ARCH} /usr/local/bin/operator-sdk

        operator-sdk version

        # Python with requirements (yaml here)
        # We could migrate to go...
        python3 -m venv sync-sources
        source sync-sources/bin/activate
        pip3 install -r requirements.txt

        # Update operator's payload and stuff
        make fetch-payload update-reference
branches:
- version: 1.17
  # upstream: …
  upstream: main
