repository: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
- controller
- entrypoint
- events
- nop
- resolvers
- sidecarlogresults
- webhook
- workingdirinit
branches:
- version: 1.16
  upstream: release-v0.62.x
