repository: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
- controller
- entrypoint
- events
- nop
- resolvers
- sidecarlogresults
- webhook
- workingdirinit
branches:
- version: 1.17
  # upstream: release-v0.65.x
  upstream: main
