repository: tektoncd-chains
upstream: tektoncd/chains
components:
  - controller
patches: &patches
- name: go1.22
  script: |
    sed -i "s%go 1.22.*%go 1.22%g" go.mod
    sed -i "s%go 1.22.*%go 1.22%g" vendor/modules.txt
    git diff > ../.konflux/patches/0000-go1.22.patch
    # clean after yourself >:D
    git checkout HEAD go.mod vendor/modules.txt
- name: go1.23
  script: |
    sed -i "s%go 1.23.*%go 1.22%g" go.mod
    sed -i "s%go 1.23.*%go 1.22%g" vendor/modules.txt
    git diff > ../.konflux/patches/0000-go1.23.patch
    # clean after yourself >:D
    git checkout HEAD go.mod vendor/modules.txt
branches:
  - upstream: release-v0.23.x
    version: next
    patches: *patches
    release: auto
