repository: tektoncd-pruner
components:
  - name: tektoncd-pruner-controller
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: next
    versions:
      - version: next
        release: auto
