---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: {{basename .Repository | hyphenize}}-{{hyphenize .Version}}-{{.Name}}
spec:
  componentName: {{.Name}}
  application: {{.Application}}-{{hyphenize .Branch}}
  build-nudges-ref:
  - operator-{{hyphenize .Branch}}-bundle
  source:
    git:
      url: https://github.com/{{.Repository}}
      dockerfileUrl: openshift/dockerfiles/{{.Name}}.Dockerfile
      revision: {{.Branch}}
