---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-plan-role-{{hyphenize .Name}}-{{hyphenize .Version.Version }}
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshots
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-plan-rolebinding-{{hyphenize .Name}}-{{hyphenize .Version.Version }}
subjects:
- kind: ServiceAccount
  name: release-registry-{{hyphenize .Name}}-{{hyphenize .Version.Version}}
  apiGroup: ""
roleRef:
  kind: Role
  name: release-plan-role-{{hyphenize .Name}}-{{hyphenize .Version.Version }}
  apiGroup: rbac.authorization.k8s.io