name: console-plugin
components:
  - name: console-plugin
    prefetch-input: |-
      [{"type": "yarn", "path": ""}]
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: release-v1.19.x
    versions:
      - next
