name: tektoncd-triggers
upstream: tektoncd/triggers
components:
  - name: controller
  - name: webhook
  - name: core-interceptors
  - name: eventlistenersink
branches:
  - name: next
    upstream: release-v0.33.x
    versions:
      - next
