name: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
  - name: controller
  - name: entrypoint
  - name: events
  - name: nop
  - name: resolvers
  - name: sidecarlogresults
  - name: webhook
  - name: workingdirinit
branches:
  - name: release-v1.20.x
    upstream: release-v1.3.x
    versions:
      - "1.20"
