name: tektoncd-results
upstream: tektoncd/results
components:
  - name: api
  - name: watcher
  - name: retention-policy-agent
branches:
  - name: next
    upstream: release-v0.14.x
    versions:
      - next
