- name: openshift-pipelines-index-4.15
  repos:
    - operator-index-4.15
- name: openshift-pipelines-index-4.16
  repos:
    - operator-index-4.16
- name: openshift-pipelines-index-4.17
  repos:
    - operator-index-4.17
- name: openshift-pipelines-index-4.18
  repos:
    - operator-index-4.18
- name: openshift-pipelines-index-4.19
  repos:
    - operator-index-4.19