- name: openshift-pipelines-core
  repos:
#    - pipelines-as-code
#    - tekton-assist
    - tekton-caches
    - tekton-kueue
#    - tektoncd-chains
#    - tektoncd-hub
    - tektoncd-pipeline
    - tektoncd-pruner
    - tektoncd-results
    - tektoncd-triggers
- name: openshift-pipelines-operator
  repos:
    - tektoncd-operator
#- name: openshift-pipelines-index-4.15
#  repos:
#    - operator-index-4.15