name: Sync Organization Labels
on:
  push:
#    paths:
#      - '.github/labels.yml'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  repository-projects: write
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync labels across org repos
        uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}
          config-file: '.github/labels.yml'
          source-repo: 'openshift-pipelines-konflux/hack' # Replace ORG with your org name

        env:
          GH_TOKEN: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}